[package]
name = "Happenstance Hodokinesis"
description = "A mod that adds a new randomised adventure/gameplay effects based on the player's Luck."
authors = ["tewlwolow"]
version = "1.0.0"
homepage = "https://www.nexusmods.com/morrowind/mods/52996"
repository = "https://github.com/tewlwolow/Happenstance-Hodokinesis"


[tools.mwse]
lua-mod = "tew.Happenstance Hodokinesis"
wait-until-initialize = false

[dependencies.mwse]
buildnumber = 3212

[dependencies.mods."Happenstance Hodokinesis"]
plugin = "Happenstance Hodokinesis.ESP"

[dependencies.mge-xe]
version = ">=0.15.0"